[".config/zsh/.zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto"
    refreshPeriod = "168h"
	[".config/zsh/.zprezto".clone]
		args = ["--recurse-submodules"]
	[".config/zsh/.zprezto".pull]
		args = ["--recurse-submodules"]

[".config/bat/syntaxes/ST-ASS"]
	type = "git-repo"
	url = "https://github.com/jfcherng-sublime/ST-ASS"

[".config/kitty/scripts/grab"]
	type = "git-repo"
	url = "https://github.com/yurikhan/kitty_grab"

[".local/bin/ffbatch"]
	type = "file"
	url = "https://raw.githubusercontent.com/Sonico98/FFBatch/main/ffbatch.sh"
	refreshPeriod = "468h"
	executable = true

[".local/bin/openArchives"]
	type = "file"
	url = "https://raw.githubusercontent.com/Sonico98/7zip-Extract/main/usr/local/bin/openArchives.sh"
	refreshPeriod = "468h"
	executable = true

[".local/bin/archiveFiles"]
	type = "file"
	url = "https://raw.githubusercontent.com/Sonico98/Dolphin-7zip-Compress/main/usr/local/bin/archiveFiles.sh"
	refreshPeriod = "468h"
	executable = true
