[[bookmark]]
key = "r"
path = "/"

[[bookmark]]
key = "h"
path = "~/"

[[bookmark]]
key = "o"
path = "/mnt/onedrive/Anime/Ore no Nounai Sentakushi ga, Gakuen Lovecome o Zenryoku de Jama Shite Iru"

[[bookmark]]
key = "a"
path = "/mnt/onedrive/Anime"
