numbered_command = false

use_trash = false
watch_files = true
xdg_open = false
xdg_open_fork = false


[display]
# default, hsplit
mode = "default"

automatically_count_files = false
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 4, 4]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "relative"

[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
max_preview_size = 99999999999 # 10485760 10MB
preview_script = "~/.dotfiles/scripts/joshuto/preview_file.sh"
preview_shown_hook_script = "~/.dotfiles/scripts/joshuto/on_preview_shown.sh"
preview_removed_hook_script = "~/.dotfiles/scripts/joshuto/on_preview_removed.sh"

[tab]
# inherit, home, root
home_page = "inherit"
