[default_view]

keymap = [
	{ keys = [ "escape" ],				command = "escape" },
	{ keys = [ "T" ],					command = "new_tab" },
	{ keys = [ "ctrl+t" ],				command = "new_tab" },
	{ keys = [ "W" ],					command = "close_tab" },
	{ keys = [ "ctrl+w" ],				command = "close_tab" },
	{ keys = [ "q" ],					command = "quit --output-current-directory" },

	{ keys = [ "R" ],					command = "reload_dirlist" },
	{ keys = [ "ctrl+h" ],				command = "toggle_hidden" },
	{ keys = [ "L" ],					command = "tab_switch 1" },
	{ keys = [ "H" ],					command = "tab_switch -1" },
	{ keys = [ "b" ],					command = "cd_bookmark" },
	{ keys = [ "B", "a" ],				command = "add_bookmark" },
	{ keys = [ "B", "r" ],				command = "shell nvim /home/sonico/.config/joshuto/bookmarks.toml" },

	{ keys = [ "alt+1" ],				command = "tab_switch_index 1" },
	{ keys = [ "alt+2" ],				command = "tab_switch_index 2" },
	{ keys = [ "alt+3" ],				command = "tab_switch_index 3" },
	{ keys = [ "alt+4" ],				command = "tab_switch_index 4" },
	{ keys = [ "alt+5" ],				command = "tab_switch_index 5" },

	{ keys = [ "1" ],					command = "numbered_command 1" },
	{ keys = [ "2" ],					command = "numbered_command 2" },
	{ keys = [ "3" ],					command = "numbered_command 3" },
	{ keys = [ "4" ],					command = "numbered_command 4" },
	{ keys = [ "5" ],					command = "numbered_command 5" },
	{ keys = [ "6" ],					command = "numbered_command 6" },
	{ keys = [ "7" ],					command = "numbered_command 7" },
	{ keys = [ "8" ],					command = "numbered_command 8" },
	{ keys = [ "9" ],					command = "numbered_command 9" },

	# arrow keys
	{ keys = [ "arrow_up" ],			command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],			command = "cursor_move_down" },
	{ keys = [ "arrow_left" ],			command = "cd .." },
	{ keys = [ "arrow_right" ], 		command = "open" },
	{ keys = [ "\n" ],					command = "open" },
	{ keys = [ "home" ],				command = "cursor_move_home" },
	{ keys = [ "end" ], 				command = "cursor_move_end" },
	{ keys = [ "page_up" ], 			command = "cursor_move_page_up" },
	{ keys = [ "page_down" ],			command = "cursor_move_page_down" },
	{ keys = [ "ctrl+u" ],				command = "cursor_move_page_up 0.5" },
	{ keys = [ "ctrl+d" ],				command = "cursor_move_page_down 0.5" },

	# vim-like keybindings
	{ keys = [ "j" ],					command = "cursor_move_down" },
	{ keys = [ "k" ],					command = "cursor_move_up" },
	{ keys = [ "h" ],					command = "cd .." },
	{ keys = [ "l" ],					command = "open" },
	{ keys = [ "g", "g" ],				command = "cursor_move_home" },
	{ keys = [ "G" ],					command = "cursor_move_end" },
	{ keys = [ "o" ],					command = "open_with" },

	{ keys = [ "[" ],					command = "preview_cursor_move_up" },
	{ keys = [ "]" ],					command = "preview_cursor_move_down" },

	{ keys = [ "z" ],					command = ":cd " },
	{ keys = [ "c", "d" ],				command = ":cd " },
	{ keys = [ "d", "d" ],				command = "cut_files" },

	{ keys = [ "y", "y" ],				command = "copy_files" },
	{ keys = [ "y", "n" ],				command = "copy_filename" },
	{ keys = [ "y", "." ],				command = "copy_filename_without_extension" },
	{ keys = [ "y", "p" ],				command = "copy_filepath" },
	{ keys = [ "y", "d" ],				command = "copy_dirpath" },
	{ keys = [ "y", "l" ],				command = "symlink_files --relative=false" },
	{ keys = [ "y", "L" ],				command = "symlink_files --relative=true" },

	{ keys = [ "delete" ],				command = "delete_files --background=true" },
	{ keys = [ "d", "D" ],				command = "delete_files --background=true" },

	{ keys = [ "p", "p" ],				command = "paste_files" },
	{ keys = [ "p", "o" ],				command = "paste_files --overwrite=true" },

	{ keys = [ "r", "a" ],				command = "rename_append" },
	{ keys = [ "r", "A" ],				command = "rename_prepend" },
	{ keys = [ "r", "b" ],				command = "bulk_rename" },

	{ keys = [ "f", "t" ],				command = ":touch " },

	{ keys = [ " " ],					command = "select --toggle=true" },
	{ keys = [ "V" ],					command = "select --all=true --toggle=true" },
	{ keys = [ "x" ],					command = "select --all=true --deselect=true" },
	{ keys = [ "v" ],					command = "toggle_visual"},

	{ keys = [ "w" ],					command = "show_tasks --exit-key=w" },
	{ keys = [ "=" ],					command = "set_mode" },
	{ keys = [ "+" ],					command = ":shell chmod +x %s" },

	{ keys = [ ":" ],					command = ":" },
	{ keys = [ ";" ],					command = ":" },

	{ keys = [ "'" ],					command = ":shell " },
	{ keys = [ "m", "k" ],				command = ":mkdir " },
	{ keys = [ "c", "w" ],				command = ":rename " },

	{ keys = [ "/" ],					command = ":search " },
	{ keys = [ "|" ],					command = ":search_inc " },
	{ keys = [ "\\" ],					command = ":search_glob " },
	{ keys = [ "ctrl+7" ],				command = "search_fzf" },
	{ keys = [ "C" ],					command = "subdir_fzf" },

	{ keys = [ "n" ],					command = "search_next" },
	{ keys = [ "N" ],					command = "search_prev" },

	{ keys = [ "s", "r" ],				command = "sort reverse" },
	{ keys = [ "s", "l" ],				command = "sort lexical" },
	{ keys = [ "s", "m" ],				command = "sort mtime" },
	{ keys = [ "s", "n" ],				command = "sort natural" },
	{ keys = [ "s", "s" ],				command = "sort size" },
	{ keys = [ "s", "e" ],				command = "sort ext" },

	{ keys = [ "m", "s" ],				command = "linemode size" },
	{ keys = [ "m", "m" ],				command = "linemode mtime" },
	{ keys = [ "m", "M" ],				command = "linemode sizemtime" },

	{ keys = [ "g", "r" ],				command = "cd /" },
	{ keys = [ "g", "c" ],				command = "cd ~/.config" },
	{ keys = [ "g", "d" ],				command = "cd ~/Downloads" },
	{ keys = [ "g", "h" ],				command = "cd ~/" },
	{ keys = [ "g", "o" ],				command = "cd /mnt/onedrive" },
	{ keys = [ "?" ],					command = "help" },

	# Custom functions
	{ keys = [ "a", "s" ],				command = "spawn /home/sonico/.dotfiles/scripts/joshuto/kitty_cmds.sh -s %s" },
	{ keys = [ "a", "u" ],				command = "spawn /home/sonico/.dotfiles/scripts/joshuto/kitty_cmds.sh -u %s" },
	{ keys = [ "a", "d" ],				command = "spawn /home/sonico/.dotfiles/scripts/joshuto/kitty_cmds.sh -d %s" },
	{ keys = [ "f1" ],					command = "spawn /home/sonico/.dotfiles/scripts/joshuto/dragon-drop.sh -e %s" },
	{ keys = [ "f2" ],					command = "spawn /home/sonico/.dotfiles/scripts/joshuto/dragon-drop.sh -t" },
	{ keys = [ "P" ],					command = "spawn /home/sonico/.dotfiles/scripts/joshuto/kitty_cmds.sh -D" },
	{ keys = [ "s", "a" ],				command = "spawn /home/sonico/.dotfiles/scripts/joshuto/separateAAC.sh" },
	{ keys = [ "backspace" ],			command = "shell kitten run-shell" },
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],			command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],			command = "cursor_move_down" },
	{ keys = [ "home" ],				command = "cursor_move_home" },
	{ keys = [ "end" ], 				command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],					command = "cursor_move_down" },
	{ keys = [ "k" ],					command = "cursor_move_up" },
	{ keys = [ "g", "g" ],				command = "cursor_move_home" },
	{ keys = [ "G" ],					command = "cursor_move_end" },

	{ keys = [ "w" ],					command = "show_tasks" },
	{ keys = [ "escape" ],				command = "show_tasks" },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],			command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],			command = "cursor_move_down" },
	{ keys = [ "home" ],				command = "cursor_move_home" },
	{ keys = [ "end" ],					command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],					command = "cursor_move_down" },
	{ keys = [ "k" ],					command = "cursor_move_up" },
	{ keys = [ "g", "g" ],				command = "cursor_move_home" },
	{ keys = [ "G" ],					command = "cursor_move_end" },

	{ keys = [ "w" ],					command = "show_tasks" },
	{ keys = [ "escape" ],				command = "show_tasks" },
]
