# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false 
sort_dir_first = true
linemode       = "size"
show_hidden    = false
show_symlink   = false
scrolloff 	   = 5

[preview]
tab_size        = 2
max_width       = 4000
max_height      = 4000
cache_dir       = ""
image_delay     = 0
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
image_filter = "triangle"
image_quality = 50
sixel_fraction = 15

[opener]
edit_newtab = [
	{ run = 'kitty_cmds -v "$@"', orphan = true, block = false,  desc = "Open in nvim", for = "unix" },
]

edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = 'code "%*"',    orphan = true, for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
	{ run = 'open "$@"', 	 orphan = true, desc = "Open", for = "macos" },
	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" }
]
reveal = [
	{ run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
	{ run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
	{ run = '''exiftool "$1"; echo "Press enter to exit test"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'kitty_cmds -e "$@"', desc = "Extract here", for = "unix" },
	{ run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
gif = [
	{ run = 'mpv --fullscreen=no --no-resume-playback --no-osc --loop "$@"', orphan = true, for = "unix" },
]
audio = [
	{ run = 'mpv --player-operation-mode=pseudo-gui --fullscreen=no --no-resume-playback "$@"', orphan = true, for = "unix" },
	{ run = 'spek "$1"', orphan = true },
	{ run = 'kid3-qt "$1"', orphan = true, desc = "Edit tags" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },

]
play = [
	{ run = 'mpv --player-operation-mode=pseudo-gui "$@"', orphan = true, for = "unix" },
	{ run = 'mpv "%1"', orphan = true, for = "windows" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]

subs = [
	{ run = '''echo sub-add "'$0'" | socat - /tmp/mpv.sock ''', desc = "Add sub to MPV", for = "unix" },
	{ run = 'aegisub "$@"', orphan = true, block = false },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ name = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "edit_newtab", "subs", "open", "reveal" ] },
	{ mime = "text/*",  use = [ "edit_newtab", "edit", "reveal" ] },
	{ mime = "image/gif", use = [ "gif", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/webm", use = [ "gif", "play", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "audio", "reveal" ] },
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit_newtab", "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit_newtab", "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
	{ mime = "application/tar",           use = [ "extract", "reveal" ] },
	{ mime = "application/gtar",          use = [ "extract", "reveal" ] },
	{ mime = "application/bzip",          use = [ "extract", "reveal" ] },
	{ mime = "application/bzip2",         use = [ "extract", "reveal" ] },
	{ mime = "application/7z-compressed", use = [ "extract", "reveal" ] },
	{ mime = "application/rar",           use = [ "extract", "reveal" ] },
	{ mime = "application/xz",              use = [ "extract", "reveal" ] },
	{ mime = "application/zstd", 			use = [ "extract", "reveal" ] },

	{ mime = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers    = 2
macro_workers    = 3
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = true

[plugin]

fetchers = [

	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
	# Mimetype
	{ id = "mime-ext", name = "*", run = "mime-ext", prio = "high" },
]

spotters = [
	{ name = "*/", run = "folder" },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*", run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# Fallback
	{ name = "*", run = "file" },
]

preloaders = [
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*",       run = "allmytoes" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# Audio
	{ mime = "audio/*", run = "exifaudio" },
	# Font
	{ mime = "font/*", run = "font" },
]

previewers = [
	{ name = "*/", run = "folder", sync = true },
	# Code
	{ mime = "text/*",                 run = "code" },
	{ mime = "*/xml",                  run = "code" },
	{ mime = "*/javascript",           run = "code" },
	{ mime = "*/wine-extension-ini", run = "code" },
	# JSON
	{ mime = "application/json", run = "json" },
	# Image
	{ mime = "image/{avif,hei?,jxl}", run = "magick" },
	{ mime = "image/svg+xml", run = "svg" },
	{ mime = "image/*",       run = "allmytoes" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# Archive
	{ mime = "application/zip",             run = "ouch" },
	{ mime = "application/gzip",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/{tar,bzip*,7z-compressed,xz,rar}", run = "ouch" },
	# Audio
	{ mime = "audio/*", run = "exifaudio"},
	# Font
	{ mime = "font/*", run = "font" },
	{ mime = "application/ms-opentype", run = "font" },
	# Empty file
	{ mime = "inode/empty", run = "empty" },
	# Fallback
	{ name = "*", run = "file" },
]

[input]
# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title = ["Create:", "Create (dir):"]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "Find next:", "Find previous:" ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Search via {n}:"
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

[confirm]
# trash
trash_title 	= "Trash {n} selected file{s}?"
trash_origin	= "center"
trash_offset	= [ 0, 0, 70, 20 ]

# delete
delete_title 	= "Permanently delete {n} selected file{s}?"
delete_origin	= "center"
delete_offset	= [ 0, 0, 70, 20 ]

# overwrite
overwrite_title   = "Overwrite file?"
overwrite_content = "Will overwrite the following file:"
overwrite_origin  = "center"
overwrite_offset  = [ 0, 0, 50, 20 ]

# quit
quit_title   = "Quit?"
quit_content = "The following task is still running, are you sure you want to quit?"
quit_origin  = "center"
quit_offset  = [ 0, 0, 50, 20 ]

[pick]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[log]
enabled = false

