[Appearance]\ncustom_palette=true\ncolor_scheme_path=/home/sonico/.config/qt5ct/colors/Pastel Pink Dark.conf
color_scheme_path=/home/sonico/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Fluent-purple-dark
